In [1]:
from knn_mom import prediction as pred

ModuleNotFoundError: No module named 'sklearn'

In [2]:
ok = pred.knn_100()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [3]:
ok

,Open,High,Low,Close,Adj Close,Volume,Close_next,Close_pct_change,rsi,stoch,...,uo,kama,mfi,adx,cci,dpo,obv,next_close,next_pct_change,stock_name
0,1750.000000,1758.900024,1748.750000,1752.400024,1752.400024,29387,0.0,0.0,49.490016,81.388268,...,51.540378,1739.594168,62.103242,25.733031,69.220078,-50.235040,133916751,1584.710010,1.326084,ACC.NS
1,1855.000000,1868.949951,1849.050049,1862.699951,1862.699951,319390,0.0,0.0,52.741139,87.285306,...,52.256432,1800.450628,66.475727,17.782732,86.265622,-35.957544,945154532,1529.899976,-0.211233,ADANIENT.NS
2,937.000000,942.950012,931.200012,936.650024,936.650024,205661,0.0,0.0,56.652533,72.074624,...,49.402387,946.107534,39.803870,23.812119,23.667617,-39.147473,166070101,810.109998,0.169732,ADANIGREEN.NS
3,663.000000,669.500000,661.200012,669.299988,669.299988,759834,0.0,0.0,57.298809,97.896809,...,56.393173,657.521393,66.165578,17.001185,84.436183,-15.857480,681438767,544.519995,1.073772,ADANIPORTS.NS
4,932.000000,939.000000,928.000000,932.700012,932.700012,62955,0.0,0.0,45.176996,67.566144,...,45.072075,886.677335,46.609995,26.932720,31.668391,-45.977499,324131027,2799.670020,0.717423,ATGL.NS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,7572.600098,7600.000000,7512.299805,7520.899902,7520.899902,50603,0.0,0.0,51.799720,33.479609,...,33.671864,7660.499963,63.726874,26.678857,-4.301675,70.297363,54987216,6119.160059,0.423950,ULTRACEMCO.NS
96,759.849976,762.349976,758.099976,759.000000,759.000000,50234,0.0,0.0,49.030751,46.619538,...,48.994769,758.588382,49.186598,15.368597,3.206133,-2.637512,260801605,621.770007,0.106183,MCDOWELL-N.NS
97,280.549988,282.850006,279.299988,281.450012,281.450012,1226337,0.0,0.0,50.496138,72.705940,...,61.209525,281.973073,59.857387,17.672843,68.662008,-3.077490,3115642119,222.690002,-0.019540,VEDL.NS
98,360.500000,363.399994,359.000000,362.549988,362.549988,425775,0.0,0.0,41.387282,46.170613,...,51.869278,364.605955,39.490410,29.915792,-66.340965,-0.044997,1209916239,294.949994,0.528412,WIPRO.NS
99,54.150002,54.200001,53.650002,53.799999,53.799999,4701803,0.0,0.0,54.459136,69.064730,...,46.272734,53.034602,73.738405,15.472013,73.867971,-1.575000,3026092860,43.480000,-0.623305,ZOMATO.NS

In [4]:
from knn_mom import metrics as mc

downtrend(df): This function takes in a dataframe df containing stock market data and returns a list of the stock names that are expected to have a downtrend (i.e., the expected percentage change in the stock price is less than -1).

In [5]:
mc.downtrend(ok)

['APOLLOHOSP.NS',
 'BPCL.NS',
 'NYKAA.NS',
 'HDFCAMC.NS',
 'HAVELLS.NS',
 'HINDALCO.NS']

uptrend(df): This function takes in a dataframe df containing stock market data and returns a list of the stock names that are expected to have an uptrend (i.e., the expected percentage change in the stock price is greater than 1).

In [6]:
mc.uptrend(ok)

['ACC.NS', 'ADANIPORTS.NS', 'DIVISLAB.NS', 'TECHM.NS', 'TITAN.NS']

up_reversal(df): This function takes in a dataframe df containing stock market data and returns a dataframe containing the stocks that are expected to be in a reversal zone (i.e., expected to have an uptrend). The reversal zone is defined as having a Relative Strength Index (RSI) less than 40 and a Stochastic oscillator (stoch) less than 30.

In [7]:
mc.up_reversal(ok)

          rsi      stoch  next_pct_change stock_name
91  33.845414  14.043499         1.547385   TECHM.NS

down_reversal(df): This function takes in a dataframe df containing stock market data and returns a dataframe containing the stocks that are expected to be in a reversal zone (i.e., expected to have a downtrend). The reversal zone is defined as having an RSI greater than 60 and a stoch greater than 80

In [8]:
mc.down_reversal(ok)

          rsi      stoch  next_pct_change   stock_name
44  66.495974  93.993666        -1.091309  HINDALCO.NS

list_pred(df): This function takes in a dataframe df containing stock market data and returns a dataframe containing the predicted percentage change in the stock price for each stock, along with the stock name. This function can be used to generate a list of predicted closing prices on the current day.

In [9]:
mc.list_pred(ok)

    next_pct_change     stock_name
0          1.326084         ACC.NS
1         -0.211233    ADANIENT.NS
2          0.169732  ADANIGREEN.NS
3          1.073772  ADANIPORTS.NS
4          0.717423        ATGL.NS
..              ...            ...
95         0.423950  ULTRACEMCO.NS
96         0.106183  MCDOWELL-N.NS
97        -0.019540        VEDL.NS
98         0.528412       WIPRO.NS
99        -0.623305      ZOMATO.NS

[100 rows x 2 columns]

In [11]:
mc.golden_crossover(ok)

               Name 50 DMA  Rs. 200 DMA  Rs.     P/E
1  Gujarat Fluoroch     3085.76      3084.03   30.07
2   Shriram Finance     1274.66      1273.36    9.42
3            Shalby      136.55       136.48   25.14
4   Dhanlaxmi Cotex       74.27        73.93   94.29
5   PTL Enterprises       31.33        31.32   17.55
6  A.K.Capital Serv      435.47       435.13    3.81
7   Huhtamaki India      201.08       201.00   33.60
8  Brigade Enterpr.      474.98       474.81  190.09
9    Times Guaranty       51.40        51.33   48.66